# Generated by Django 4.0.6 on 2022-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userderived',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
