# Generated by Django 4.0.6 on 2022-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userderived_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userderived',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
